### ISSUE TITLE
Script fails?

### ISSUE THREAD

**Issue by michielbdejong** [muze-nl/federated-timesheets-tests#4]
When I run `./test-prejournal.sh` I see:
```
[...]
[+] Running 8/8
 ⠿ Network federated-timesheets-tests_default             Created                                                         0.1s
 ⠿ Container federated-timesheets-tests-prejournal-db-1   Start...                                                        0.6s
 ⠿ Container federated-timesheets-tests-timeld-gateway-1  Star...                                                         1.0s
 ⠿ Container federated-timesheets-tests-tikiwiki-db-1     Started                                                         0.6s
 ⠿ Container federated-timesheets-tests-mailhog-1         Started                                                         0.8s
 ⠿ Container federated-timesheets-tests-timeld-cli-1      Started                                                         1.0s
 ⠿ Container federated-timesheets-tests-prejournal-1      Started                                                         1.5s
 ⠿ Container federated-timesheets-tests-tikiwiki-1        Started                                                         1.5s
--- Initializing timeld
Error: No such container: federation-tests_timeld-cli_1
--- Extracted key: 
--- Installing tikiwiki
Error: No such container: federation-tests_tikiwiki_1
--- Setting up environment for prejournal
Error: No such container:path: federation-tests_prejournal_1:/app
Looking for .env in /app
<br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host &quot;prejournal-db&quot; (172.18.0.2) and accepting
        TCP/IP connections on port 5432? in /app/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28
Stack trace:
#0 /app/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php(28): PDO-&gt;__construct('pgsql:host=prej...', 'prejournal_test', '123456', Array)
#1 /app/vendor/doctrine/dbal/src/Connection.php(341): Doctrine\DBAL\Driver\PDO\PgSQL\Driver-&gt;connect(Array)
#2 /app/vendor/doctrine/dbal/src/Connection.php(1531): Doctrine\DBAL\Connection-&gt;connect()
#3 /app/vendor/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection-&gt;getWrappedConnection()
#4 /app/src/database.php(57): Doctrine\DBAL\Connection-&gt;executeQuery('SELECT id,passw...', Array)
#5 /app/src/platform.php(41): validateUser('admin', 'secret')
#6 /app/src/platform.php(134): getUser()
#7 /app/src/server.php(24): getContext()
#8 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host &quot;prejournal-db&quot; (172.18.0.2) and accepting
        TCP/IP connections on port 5432? in /app/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30
Stack trace:
#0 /app/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php(34): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /app/vendor/doctrine/dbal/src/Connection.php(341): Doctrine\DBAL\Driver\PDO\PgSQL\Driver-&gt;connect(Array)
#2 /app/vendor/doctrine/dbal/src/Connection.php(1531): Doctrine\DBAL\Connection-&gt;connect()
#3 /app/vendor/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection-&gt;getWrappedConnection()
#4 /app/src/database.php(57): Doctrine\DBAL\Connection-&gt;executeQuery('SELECT id,passw...', Array)
#5 /app/src/platform.php(41): validateUser('admin', 'secret')
#6 /app/src/platform.php(134): getUser()
#7 /app/src/server.php(24): getContext()
#8 {main}

Next Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host &quot;prejournal-db&quot; (172.18.0.2) and accepting
        TCP/IP connections on port 5432? in /app/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81
Stack trace:
#0 /app/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter-&gt;convert(Object(Doctrine\DBAL\Driver\PDO\Exception), NULL)
#1 /app/vendor/doctrine/dbal/src/Connection.php(1757): Doctrine\DBAL\Connection-&gt;handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), NULL)
#2 /app/vendor/doctrine/dbal/src/Connection.php(343): Doctrine\DBAL\Connection-&gt;convertException(Object(Doctrine\DBAL\Driver\PDO\Exception))
#3 /app/vendor/doctrine/dbal/src/Connection.php(1531): Doctrine\DBAL\Connection-&gt;connect()
#4 /app/vendor/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection-&gt;getWrappedConnection()
#5 /app/src/database.php(57): Doctrine\DBAL\Connection-&gt;executeQuery('SELECT id,passw...', Array)
#6 /app/src/platform.php(41): validateUser('admin', 'secret')
#7 /app/src/platform.php(134): getUser()
#8 /app/src/server.php(24): getContext()
#9 {main}
  thrown in <b>/app/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php</b> on line <b>81</b><br />
--- Connecting prejournal to tiki and timeld
Error: No such container:path: federation-tests_prejournal_1:/app
--- Entering timesheet entry in prejournal
Looking for .env in /app
<br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host &quot;prejournal-db&quot; (172.18.0.2) and accepting
        TCP/IP connections on port 5432? in /app/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28
Stack trace:
#0 /app/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php(28): PDO-&gt;__construct('pgsql:host=prej...', 'prejournal_test', '123456', Array)
#1 /app/vendor/doctrine/dbal/src/Connection.php(341): Doctrine\DBAL\Driver\PDO\PgSQL\Driver-&gt;connect(Array)
#2 /app/vendor/doctrine/dbal/src/Connection.php(1531): Doctrine\DBAL\Connection-&gt;connect()
#3 /app/vendor/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection-&gt;getWrappedConnection()
#4 /app/src/database.php(57): Doctrine\DBAL\Connection-&gt;executeQuery('SELECT id,passw...', Array)
#5 /app/src/platform.php(37): validateUser('alice', 'alice123')
#6 /app/src/platform.php(134): getUser()
#7 /app/src/server.php(24): getContext()
#8 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host &quot;prejournal-db&quot; (172.18.0.2) and accepting
        TCP/IP connections on port 5432? in /app/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30
Stack trace:
#0 /app/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php(34): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /app/vendor/doctrine/dbal/src/Connection.php(341): Doctrine\DBAL\Driver\PDO\PgSQL\Driver-&gt;connect(Array)
#2 /app/vendor/doctrine/dbal/src/Connection.php(1531): Doctrine\DBAL\Connection-&gt;connect()
#3 /app/vendor/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection-&gt;getWrappedConnection()
#4 /app/src/database.php(57): Doctrine\DBAL\Connection-&gt;executeQuery('SELECT id,passw...', Array)
#5 /app/src/platform.php(37): validateUser('alice', 'alice123')
#6 /app/src/platform.php(134): getUser()
#7 /app/src/server.php(24): getContext()
#8 {main}

Next Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host &quot;prejournal-db&quot; (172.18.0.2) and accepting
        TCP/IP connections on port 5432? in /app/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:81
Stack trace:
#0 /app/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter-&gt;convert(Object(Doctrine\DBAL\Driver\PDO\Exception), NULL)
#1 /app/vendor/doctrine/dbal/src/Connection.php(1757): Doctrine\DBAL\Connection-&gt;handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), NULL)
#2 /app/vendor/doctrine/dbal/src/Connection.php(343): Doctrine\DBAL\Connection-&gt;convertException(Object(Doctrine\DBAL\Driver\PDO\Exception))
#3 /app/vendor/doctrine/dbal/src/Connection.php(1531): Doctrine\DBAL\Connection-&gt;connect()
#4 /app/vendor/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection-&gt;getWrappedConnection()
#5 /app/src/database.php(57): Doctrine\DBAL\Connection-&gt;executeQuery('SELECT id,passw...', Array)
#6 /app/src/platform.php(37): validateUser('alice', 'alice123')
#7 /app/src/platform.php(134): getUser()
#8 /app/src/server.php(24): getContext()
#9 {main}
  thrown in <b>/app/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php</b> on line <b>81</b><br />
--- Fetching report from timeld
Error: No such container: federation-tests_timeld-cli_1
--- Fetching report from tikiwiki
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   273  100   273    0     0   133k      0 --:--:-- --:--:-- --:--:--  133k

------------------------------
Federation to TimeLD failed
------------------------------
------------------------------

--------------------------------
Federation to tikiwiki failed
--------------------------------
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.54 (Debian) Server at localhost Port 8180</address>
</body></html>
--------------------------------
[+] Running 8/8
 ⠿ Container federated-timesheets-tests-prejournal-1      Removed                                                        10.5s
 ⠿ Container federated-timesheets-tests-timeld-gateway-1  Remo...                                                        10.5s
 ⠿ Container federated-timesheets-tests-timeld-cli-1      Removed                                                        10.4s
 ⠿ Container federated-timesheets-tests-mailhog-1         Removed                                                         0.3s
 ⠿ Container federated-timesheets-tests-tikiwiki-1        Removed                                                         1.2s
 ⠿ Container federated-timesheets-tests-tikiwiki-db-1     Removed                                                        10.2s
 ⠿ Container federated-timesheets-tests-prejournal-db-1   Remov...                                                        0.3s
 ⠿ Network federated-timesheets-tests_default             Removed                                                         0.1s

----------------------------
Prejournal federation failed
----------------------------
```

**Comment by michielbdejong** [comment]
I think you need to add a db health check like the one we use in https://github.com/pondersource/CYB/blob/f946301/cyb-app/docker-compose.yaml#L123-L133

**Comment by ylebre** [comment]
Hm, it looks to me like an issue with the naming of the containers. It looks like gitpod has a different naming scheme, so I think we need to provide those.

**Comment by michielbdejong** [comment]
Yes, you're probably using Docker compose v1, and GitPod uses v2, see https://stackoverflow.com/questions/69464001/docker-compose-container-name-use-dash-instead-of-underscore
You could use an env var so that the code will run on both Docker Compose versions.

**Comment by ylebre** [comment]
Should be fixed in https://github.com/muze-nl/federated-timesheets-tests/pull/6 by adding the compatiblity flag + project name.
